version: '2'

services:
  data_creator:
    build: data_creator
    container_name: datacreator
    image: bestteam/datacreator:latest
    restart: always
    volumes:
      - data:/noisy_student/src/data-mscoco
  noisy_student:
    build: .
    container_name: noisystudent
    image: bestteam/noisystudent:latest
    restart: always
    volumes:
      - data:/noisy_student
    depends_on:
      - data_creator
volumes:
  data:
