version: '2'

services:
  noisy_student:
    build: .
    container_name: noisystudent
    image: bestteam/noisystudent:latest
    restart: always
    volumes:
      - data:/noisy_student
    depends_on:
      - data_creator
  data_creator:
    build: data_creator
    container_name: datacreator
    image: bestteam/datacreator:latest
    restart: always
    volumes:
      - data:/noisy_student
volumes:
  data:
